spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/salon_queue}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:atharva@07raje}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
